# Generated by Django 4.2.16 on 2024-10-24 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=150, verbose_name='Действие')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место выполнения привычки')),
                ('time', models.TimeField(verbose_name='Время выполнения привычки')),
                ('is_pleasant_habit', models.BooleanField(blank=True, default=False, null=True, verbose_name='Признак приятной привычки')),
                ('periodicity', models.CharField(choices=[('1 time in 1 days', '1 раз в день'), ('1 time in 7 days', '1 раз в неделю')], default='1 time in 1 days', max_length=100, verbose_name='Периодичность')),
                ('reward', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вознаграждение')),
                ('time_to_complete', models.PositiveIntegerField(verbose_name='Время на выполнение привычки')),
                ('is_publicity', models.BooleanField(blank=True, default=False, null=True, verbose_name='Признак публичности')),
                ('next_reminder', models.DateField(blank=True, null=True, verbose_name='Следующее напоминание')),
                ('associated_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habits', to='habits.habit', verbose_name='Связанная привычка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cоздатель привычки')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
