# Generated by Django 4.2.16 on 2024-11-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.CharField(choices=[('1 time in 1 days', '1 раз в день'), ('1 time in 7 days', '1 раз в неделю')], default='1 time in 1 days', max_length=100, verbose_name='Периодичность'),
        ),
    ]
